#!/bin/bash


sshpass -p PASSWORD sftp -oHostKeyAlgorithms=+ssh-rsa -oStrictHostKeyChecking=no -r -P 9666 mark@markphone:/Pictures/Telegram/*
sshpass -p PASSWORD sftp -oHostKeyAlgorithms=+ssh-rsa -oStrictHostKeyChecking=no -r -P 9666 mark@markphone:/Camera/*
sshpass -p PASSWORD sftp -oHostKeyAlgorithms=+ssh-rsa -oStrictHostKeyChecking=no -r -P 9666 mark@markphone:/Download/*
sshpass -p PASSWORD sftp -oHostKeyAlgorithms=+ssh-rsa -oStrictHostKeyChecking=no -r -P 9666 mark@markphone:/0/Movies/Telegram/*
