#!/bin/bash

target=geordi

display_usage() {
  echo "Usage: transfermovies [-h][-k][-s <string>]"
  echo ""
  echo "Demonstrates how to do argument parsing in bash using getopts"
  echo ""
  echo "-m, --help        Target the movie directory (default)"
  echo "-t, --help        Target the TV directory"
  echo "-d, --help        Target the documentary directory"
  echo "-k, --help        Target the kids directory"
  echo "-s, --help        Source directory. If none is given, will use the current working directory"
}

while getopts "hmktds:" opt; do #variables that take an argument are followed by a colon
  case ${opt} in
    h | \? | help )
      display_usage; 
      exit 0 
      ;;
    m )
      movie=1
      ;;
    k )
      kids=1
      ;;
    t )
      tv=1
      ;;
    d )
      docs=1
      ;;
    s )
      svar=$OPTARG
      ;;
    esac
done

if [ -z $svar ]; then
    dir="."
else
    dir=$svar
fi


if [ -v movie ]; then
    tdir="mark@$target:/mnt/data3/movie"
elif [ -v kids ]; then
    tdir="mark@$target:/mnt/data2/kids"
elif [ -v tv ]; then
    tdir="mark@$target:/mnt/data2/tv"
elif [ -v docs ]; then
    tdir="mark@$target:/mnt/data2/documentaries"
else  # default to movie
    movie=1
    tdir="mark@$target:/mnt/data3/movie"
fi

# Special non-alphabetical handling for documentaries
if [ -v docs ]; then
    for doctype in arts business_economics cspan food games health_medicine history nature other politics religion_mythology science_engineering_math sports technology true_crime
    do
        if [ -z $dir/$doctype ]; then
	    echo "Processing directory" $dir/$doctype
	    rsync -azP $dir/$doctype/* "$tdir/$doctype"
        fi
    done
else
    echo "Processing directory" $dir
    for x in {0..9}; do
	files=$(ls $dir/$x* 2>/dev/null)
	if [ -z "${files// }" ]; then
	    continue
	fi
	echo $dir/$x* " " $tdir/$x
	rsync -azP $dir/$x* "$tdir/0-9"
    done


    for x in {A..Z}; do
	files=$(ls $dir/$x* 2>/dev/null)
	if [ -z "${files// }" ]; then
	    continue
	fi
	echo $dir/$x* " " $tdir/$x
	rsync -azP $dir/$x* $tdir/$x
    done
fi

