#!/bin/bash

start_time=$(date +%s)

#data
if mountpoint -q /mnt/backup; then
    echo "/mnt/data/"
    rsync -aHAXxv --delete --partial --info=progress2 --exclude='lost+found/' -e "ssh -o Compression=no" mark@geordi:/mnt/data/ /mnt/backup/data

    echo "/mnt/backup/ontime"
    rsync -aHAXxv --delete --partial --info=progress2 -e "ssh -o Compression=no" mark@geordi:/mnt/backup/onetime/ /mnt/backup/onetime
else
    echo "/mnt/backup is not mounted"
fi

elapsed=$(( $(date +%s) - start_time ))
echo "Time to backup: ${elapsed} seconds"
