alias e='emacs'
alias movie='cd /mnt/data3/movie'
alias tv='cd /mnt/data2/tv'
alias tv2='cd /mnt/data4/tv'
alias unsorted='cd /mnt/data2/unsorted'
alias kids='cd /mnt/data3/kids'
alias doc='cd /mnt/data3/documentaries'
alias docs='cd /mnt/data3/documentaries'
alias pics='cd /mnt/data/pictures/my_photos'
alias ytdl='yt-dlp -o "%(title)s.f%(format_id)s.%(ext)s"'
alias dur='exiftool -api LargeFileSupport=1 -j -Duration '
