#!/bin/bash

start_time=$(date +%s)

#data
if mountpoint -q /mnt/data; then
    echo "/mnt/data/"
    rsync -aHAXxv --delete --partial --info=progress2 -e "ssh -o Compression=no" mark@geordi:/mnt/data/ /mnt/data/
else
    echo "/mnt/data is not mounted"
fi


#onetime
echo "/mnt/backup/ontime"
rsync -aHAXxv --delete --partial --info=progress2 -e "ssh -o Compression=no" mark@geordi:/mnt/backup/onetime/ /onetime


#data2
if mountpoint -q /mnt/data2; then
    echo "/mnt/data2/"
    rsync -aHAXxv --delete --partial --info=progress2 -e "ssh -o Compression=no" mark@geordi:/mnt/data2/ /mnt/data2/    
else
    echo "/mnt/data2 is not mounted"
fi


#data3
if mountpoint -q /mnt/data3; then
    echo "/mnt/data3/"
    rsync -aHAXxv --delete --partial --info=progress2 -e "ssh -o Compression=no" mark@geordi:/mnt/data3/ /mnt/data3/
else
    echo "/mnt/data3 is not mounted"
fi

elapsed=$(( $(date +%s) - start_time ))
echo "Time to backup: ${elapsed} seconds"
